/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * penTablet.java
 *
 * Created on Sep 21, 2013, 5:22:51 PM
 */
package LED;

/**
 *
 * @author Administrator
 */
import java.awt.*;
import java.util.*;
import javax.swing.event.*;
import java.io.*;
import java.awt.event.*;
import javax.swing.*;

public class penTablet extends javax.swing.JFrame {

    boolean enter=false;
    int x=0,y=0;
    int xy[][];
    int i=0;
    boolean cl=false;
    boolean dum[][]=new boolean[30][];    
    /** Creates new form penTablet */
    public penTablet() {
        initComponents();
        xy=new int[2][];
        xy[0]=new int[1000];
        xy[1]=new int[1000];
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        penTAB = new JPanel(){

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                if(cl==false){
                    for(int i=0;i<1000;i++)
                    g.fillRect(xy[0][i], xy[1][i], 2, 2);
                }
                if(cl)
                Paint(g);
            }
        };
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Play on Pen Tablet");
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Write using pen Tab in specified Area:");

        penTAB.setBackground(new java.awt.Color(204, 204, 204));
        penTAB.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        penTAB.setPreferredSize(new java.awt.Dimension(300, 80));
        penTAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Release(evt);
            }
        });
        penTAB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Move(evt);
            }
        });

        javax.swing.GroupLayout penTABLayout = new javax.swing.GroupLayout(penTAB);
        penTAB.setLayout(penTABLayout);
        penTABLayout.setHorizontalGroup(
            penTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        penTABLayout.setVerticalGroup(
            penTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jButton1.setText("See IT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(penTAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penTAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Enter
    enter=true;
}//GEN-LAST:event_Enter

private void Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit
    enter=false;
}//GEN-LAST:event_Exit

private void Move(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Move
    if(enter && i<1000){
        x=evt.getX();
        y=evt.getY();
        xy[0][i]=x;
        xy[1][i]=y;
        i++;
    }
}//GEN-LAST:event_Move

private void Release(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Release
    repaint();
}//GEN-LAST:event_Release

private void Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click
    arrange();
    cl=true;
    repaint();
}//GEN-LAST:event_Click

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    arrange();
    writeText();
}//GEN-LAST:event_jButton1ActionPerformed


public void arrange(){
    for(int i=0;i<30;i++){
        dum[i]=new boolean[8];
        for(int m=0;m<8;m++){
            dum[i][m]=false;
        }
    }
    
    for(int i=0;i<1000;i++){
        int j=0,k=0;
        for(j=10;j<=300;j++){
            if(xy[0][i]<=j)
                break;
        }
        for(k=10;k<=80;k++){
            if(xy[1][i]<=k)
                break;
        }
        int ledx=j/10-1;
        int ledy=k/10-1;
        
        for(int m=0;m<8;m++){
            dum[ledx][ledy]=true;
        }
    }
}
public void Paint(Graphics g){
    for(int i=0;i<30;i++){
        for(int j=0;j<8;j++){
            if(dum[i][j])
                g.fillRect(i*10, j*10, 10, 10);
        }
    }
}

public void writeText(){
    try{
        File f=new File("Data.txt");
        DataOutputStream out = new DataOutputStream(new FileOutputStream(f));
        out.flush();
        for(int i=0;i<30;i++){
            for(int j=0;j<8;j++){
                if(dum[i][j]){
                    out.writeBytes(String.valueOf(j+1));
                }
            }
            out.writeBytes("N"+"\n");
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage(), "Error in program",JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new penTablet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel penTAB;
    // End of variables declaration//GEN-END:variables
}
